$Target = Join-Path $env:LOCALAPPDATA "物思"
Write-Host "Target: $Target"
$pyDir = Join-Path $env:LOCALAPPDATA "Programs\Python\Python310"
$pyScripts = Join-Path $env:LOCALAPPDATA "Programs\Python\Python310\Scripts"
$env:PATH = "$pyDir;$pyScripts;$env:PATH"
Write-Host "PATH set: $env:PATH"
